# Project information
site_name: 'Ahmed Abdou'
site_description: ''
site_author: 'Ahmed Abdou'
site_url: 'https://ahmed.nu'
copyright: 'Creative Commons'


extra_css:
  - 'css/extra.css'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/amaabdou/'
    - type: 'twitter'
      link: 'https://twitter.com/ama_abdou'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/ahmedmaabdou/'

theme: 
  name: 'material'
  palette:
    primary: 'white'
    accent: 'white'
    
markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.superfences

nav:
  - Hi: index.md